# elderlyCare

trigger:
- elderlyCare-Sandbox-branch

pool:
  vmImage: ubuntu-latest

stages: 
  - stage: 'Junit'
    displayName: 'Junit stage'
    jobs:
    - job: 'JunitTest'
      displayName: 'Running Unit Test'
      steps:
      - script: echo 'Running demo app unit test'
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'test'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          codeCoverageToolOption: 'JaCoCo'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
          pmdRunAnalysis: true
          findBugsRunAnalysis: true
   
